--GROUP BY AND HAVING CLAUSE

--HOW MANY EMPLOYEES WHO ARE IN DIFFERENT DEPARTMENTS WISE IN THE ORGANIZATION.

SELECT COUNT(EMPLOYEE_ID) AS COUNT,DEPARTMENT_ID FROM EMPLOYEE
GROUP BY DEPARTMENT_ID

-- LIST OUT DEPARTMENT WISE MAXIMUM SALARY, MINIMUM SALARY, AVERAGE SALARIES OF THE 
--EMPLOYEES.

SELECT MAX(SALARY) AS MAXIMUM,MIN(SALARY) AS MINIMUM,AVG(SALARY) AS AVERAGE,DEPARTMENT_ID
FROM EMPLOYEE
GROUP BY DEPARTMENT_ID

-- LIST OUT JOB WISE MAXIMUM SALARY, MINIMUM SALARY, AVERAGE SALARIES OF THE 
--EMPLOYEES.

SELECT MAX(SALARY) AS MAXIMUM,MIN(SALARY) AS MINIMUM,AVG(SALARY) AS AVERAGE,JOB_ID
FROM EMPLOYEE
GROUP BY JOB_ID

-- LIST OUT THE NUMBER OF EMPLOYEES JOINED IN EVERY MONTH IN ASCENDING ORDER.

SELECT MONTH([HIRE DATE]) AS MONTH,COUNT(EMPLOYEE_ID)AS COUNT FROM EMPLOYEE
GROUP BY [HIRE DATE]

-- LIST OUT THE DEPARTMENT ID HAVING ATLEAST FOUR EMPLOYEES

SELECT DEPARTMENT_ID FROM EMPLOYEE
GROUP BY DEPARTMENT_ID
HAVING COUNT(*)>=4

-- HOW MANY EMPLOYEES JOINED IN JANUARY MONTH.

SELECT [HIRE DATE],FIRST_NAME
FROM EMPLOYEE
GROUP BY [HIRE DATE],FIRST_NAME
HAVING MONTH([HIRE DATE])=1

--. HOW MANY EMPLOYEES JOINED IN JANUARY OR SEPTEMBER MONTH.

SELECT [HIRE DATE],FIRST_NAME
FROM EMPLOYEE
GROUP BY [HIRE DATE],FIRST_NAME
HAVING MONTH([HIRE DATE]) IN (1,9)

-- HOW MANY EMPLOYEES WERE JOINED EACH MONTH IN 1985

SELECT MONTH([HIRE DATE]) AS [MONTH], COUNT(*) AS TOTAL_JOINING
FROM EMPLOYEE 
WHERE YEAR([HIRE DATE])=1985
GROUP BY MONTH([HIRE DATE])
ORDER BY MONTH ASC

--HOW MANY EMPLOYEES WERE JOINED IN MARCH 1985?

SELECT MONTH([HIRE DATE]) AS [MONTH], COUNT(*) AS JOINING
FROM EMPLOYEE
WHERE YEAR([HIRE DATE])=1985
GROUP BY MONTH([HIRE DATE])
HAVING MONTH([HIRE DATE])=3

-- WHICH IS THE DEPARTMENT ID, HAVING GREATER THAN OR EQUAL TO 3 EMPLOYEES JOINED IN 
--APRIL 1985?

SELECT DEPARTMENT_ID
FROM EMPLOYEE
WHERE YEAR([HIRE DATE])=1985 AND MONTH([HIRE DATE])= 4
GROUP BY DEPARTMENT_ID
HAVING COUNT(DEPARTMENT_ID)>=3

-- LIST OUT THE NUMBER OF EMPLOYEES FOR EACH MONTH AND YEAR, IN THE ASCENDING 
--ORDER BASED ON THE YEAR, MONTH.

SELECT YEAR([HIRE DATE]) AS YEAR,MONTH([HIRE DATE]) AS MONTH,
COUNT(*) FROM EMPLOYEE 
GROUP BY EMPLOYEE_ID,[HIRE DATE]
ORDER BY YEAR([HIRE DATE]) , MONTH([HIRE DATE]) 






