


--JOINS---

-- LIST OUT EMPLOYEES WITH THEIR DEPARTMENT NAMES.

SELECT E.FIRST_NAME,D.NAME,D.DEPARTMENT_ID
FROM EMPLOYEE E
JOIN DEPARTMENT D ON E.DEPARTMENT_ID=D.DEPARTMENT_ID
GROUP BY D.NAME,D.DEPARTMENT_ID,E.FIRST_NAME

-- DISPLAY EMPLOYEES WITH THEIR DESIGNATIONS.

SELECT E.FIRST_NAME,J.DESIGNATION
FROM EMPLOYEE E,JOB J
WHERE E.JOB_ID=J.JOB_ID

 SELECT E.FIRST_NAME,J.DESIGNATION
 FROM EMPLOYEE E
 JOIN JOB J ON J.JOB_ID=E.JOB_ID

 -- DISPLAY THE EMPLOYEES WITH THEIR DEPARTMENT NAMES AND REGIONAL GROUPS.

 SELECT E.FIRST_NAME,D.NAME,L.CITY
 FROM EMPLOYEE E
 JOIN DEPARTMENT D ON E.DEPARTMENT_ID=D.DEPARTMENT_ID
 JOIN [LOCATION] L ON D.LOCATION_ID=L.LOCATION_ID

--HOW MANY EMPLOYEES WHO ARE WORKING IN DIFFERENT DEPARTMENTS AND DISPLAY WITH 
--DEPARTMENT NAMES.

SELECT COUNT(EMPLOYEE_ID) AS COUNT,D.NAME 
FROM EMPLOYEE E
JOIN DEPARTMENT D ON E.DEPARTMENT_ID=D.DEPARTMENT_ID
GROUP BY D.NAME

-- HOW MANY EMPLOYEES WHO ARE WORKING IN SALES DEPARTMENT.

SELECT COUNT(EMPLOYEE_ID) AS COUNT
FROM EMPLOYEE E
JOIN DEPARTMENT D ON E.DEPARTMENT_ID=D.DEPARTMENT_ID
WHERE D.NAME='SALES'

--WHICH IS THE DEPARTMENT HAVING GREATER THAN OR EQUAL TO 5
--EMPLOYEES AND DISPLAY THE DEPARTMENT NAMES IN ASCENDING ORDER

SELECT COUNT(EMPLOYEE_ID)AS COUNT, D.DEPARTMENT_ID,D.NAME
FROM EMPLOYEE E
JOIN DEPARTMENT D ON E.DEPARTMENT_ID=D.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_ID,D.NAME
HAVING COUNT(E.EMPLOYEE_ID)>=5
ORDER BY D.NAME ASC

-- HOW MANY JOBS IN THE ORGANIZATION WITH DESIGNATIONS

SELECT COUNT(DISTINCT(J.JOB_ID)) AS COUNT ,J.DESIGNATION
 FROM EMPLOYEE E
 JOIN JOB J ON E.JOB_ID=E.JOB_ID
 JOIN DEPARTMENT D ON E.DEPARTMENT_ID=D.DEPARTMENT_ID
 GROUP BY J.DESIGNATION

-- HOW MANY EMPLOYEES ARE WORKING IN "NEW YORK"

SELECT COUNT(EMPLOYEE_ID) AS COUNT,L.CITY
FROM EMPLOYEE E
JOIN DEPARTMENT D ON E.DEPARTMENT_ID=D.DEPARTMENT_ID
JOIN [LOCATION] L ON D.LOCATION_ID=L.LOCATION_ID
WHERE L.CITY='NEW YORK'
GROUP BY L.CITY

-- DISPLAY THE EMPLOYEE DETAILS WITH SALARY GRADES.

SELECT *,
CASE
WHEN SALARY >=2500 
THEN 'GOOD'
WHEN SALARY >1500
THEN 'AVERAGE'
ELSE 'POOR'
END AS GRADE
FROM EMPLOYEE

-- LIST OUT THE NO. OF EMPLOYEES ON GRADE WISE.

SELECT COUNT(*) AS COUNT,
CASE
WHEN SALARY >=2500 
THEN 'GOOD'
WHEN SALARY >1500
THEN 'AVERAGE'
ELSE 'POOR'
END AS GRADE
FROM EMPLOYEE E
GROUP BY SALARY

-- DISPLAY THE EMPLOYEE SALARY GRADES AND NO. OF EMPLOYEES BETWEEN 2000 TO 
-- 5000 RANGE OF SALARY.

SELECT SALARY,
CASE
WHEN SALARY >=2500 
THEN 'GOOD'
WHEN SALARY >1500
THEN 'AVERAGE'
ELSE 'POOR'
END AS GRADE
FROM EMPLOYEE
WHERE SALARY BETWEEN 2000 AND 5000



